---
AWSTemplateFormatVersion: 2010-09-09
Description: AppStream 2.0 on-demand fleet and stack
Parameters:
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-with-gateway-endpoints
  IamStackName:
    Description: Set the S3 stack name.
    Type: String
    Default: s3-and-iam-for-appstream
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: vdi
  ImageName:
    Description: Set the AppStream 2.0 image name.
    Type: String
    Default: al2-with-docker
  InstanceType:
    Description: Set the AppStream 2.0 instance type.
    Type: String
    Default: stream.standard.small
  DesiredInstances:
    Description: Set the desired number of streaming instances.
    Type: Number
    Default: 1
  EnableDefaultInternetAccess:
    Description: Enable the default internet access.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  PreferredProtocol:
    Description: Set the streaming protocol.
    Type: String
    Default: UDP
    AllowedValues:
      - TCP
      - UDP
  MaxUserDurationInSeconds:
    Description: Set the max user duration in seconds.
    Type: Number
    MinValue: 600
    MaxValue: 360000
    Default: 57600
  DisconnectTimeoutInSeconds:
    Description: Set the disconnect timeout in seconds.
    Type: Number
    MinValue: 60
    MaxValue: 360000
    Default: 900
  IdleDisconnectTimeoutInSeconds:
    Description: Set the idle disconnect timeout in seconds.
    Type: Number
    MinValue: 0
    MaxValue: 3600
    Default: 900
Resources:
  AppStreamSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${ProjectName}-appstream-security-group
      GroupDescription: AppStream 2.0 security group
      VpcId:
        Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-security-group
  AppStreamFleet:
    Type: AWS::AppStream::Fleet
    Properties:
      Name: !Sub ${ProjectName}-appstream-ondemand-fleet-${ImageName}
      DisplayName: !Sub ${ProjectName}-appstream-ondemand-fleet-${ImageName}
      Description: AppStream 2.0 on-demand fleet
      FleetType: ON_DEMAND
      ImageName: !Ref ImageName
      InstanceType: !Ref InstanceType
      ComputeCapacity:
        DesiredInstances: !Ref DesiredInstances
      MaxUserDurationInSeconds: !Ref MaxUserDurationInSeconds
      DisconnectTimeoutInSeconds: !Ref DisconnectTimeoutInSeconds
      IdleDisconnectTimeoutInSeconds: !Ref IdleDisconnectTimeoutInSeconds
      StreamView: DESKTOP
      IamRoleArn:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-AppStreamServiceRoleArn
      EnableDefaultInternetAccess: !Ref EnableDefaultInternetAccess
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet1
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet2
        SecurityGroupIds:
          - !Ref AppStreamSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-ondemand-fleet-${ImageName}
  AppStreamStack:
    Type: AWS::AppStream::Stack
    Properties:
      Name: !Sub ${ProjectName}-appstream-ondemand-fleet-stack-${ImageName}
      DisplayName: !Sub ${ProjectName}-appstream-ondemand-fleet-stack-${ImageName}
      Description: AppStream 2.0 on-demand fleet stack
      StreamingExperienceSettings:
        PreferredProtocol: !Ref PreferredProtocol
      StorageConnectors:
        - ConnectorType: HOMEFOLDERS
      UserSettings:
        - Action: CLIPBOARD_COPY_FROM_LOCAL_DEVICE
          Permission: ENABLED
        - Action: CLIPBOARD_COPY_TO_LOCAL_DEVICE
          Permission: ENABLED
        - Action: FILE_DOWNLOAD
          Permission: ENABLED
        - Action: FILE_UPLOAD
          Permission: ENABLED
        - Action: PRINTING_TO_LOCAL_DEVICE
          Permission: ENABLED
      # ApplicationSettings:
      #   Enabled: true
      #   SettingsGroup: String
      # AttributesToDelete:
      #   - String
      # EmbedHostDomains:
      #   - String
      # FeedbackURL: String
      # RedirectURL: String
      # AccessEndpoints:
      #   - EndpointType: STREAMING
      #     VpceId: !Ref AppStreamStreamingInterfaceEndpoint
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-ondemand-fleet-stack-${ImageName}
  AppStreamStackFleetAssociation:
    Type: AWS::AppStream::StackFleetAssociation
    Properties:
      FleetName: !Ref AppStreamFleet
      StackName: !Ref AppStreamStack
#   AppStreamStreamingInterfaceEndpoint:
#     Type: AWS::EC2::VPCEndpoint
#     Properties:
#       PrivateDnsEnabled: true
#       SubnetIds:
#         - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
#       SecurityGroupIds:
#         - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
#       ServiceName: !Sub com.amazonaws.${AWS::Region}.appstream.streaming
#       VpcEndpointType: Interface
#       VpcId:
#         Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-VPC
Outputs:
  AppStreamSecurityGroup:
    Value: !Ref AppStreamSecurityGroup
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamSecurityGroup
  AppStreamFleet:
    Value: !Ref AppStreamFleet
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamFleet
  AppStreamStack:
    Value: !Ref AppStreamStack
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamStack
