---
AWSTemplateFormatVersion: 2010-09-09
Description: AppStream 2.0 image builders
Parameters:
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-with-gateway-endpoints
  S3StackName:
    Description: Set the S3 stack name.
    Type: String
    Default: s3-and-iam-for-appstream
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: vdi
  InstanceType:
    Description: Set the AppStream 2.0 instance type.
    Type: String
    Default: stream.standard.small
  EnableDefaultInternetAccess:
    Description: Enable the AppStream 2.0 default internet access.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Resources:
  AppStreamWindowsImageBuilder:
    Type: AWS::AppStream::ImageBuilder
    Properties:
      Name: !Sub ${ProjectName}-appstream-windows-image-builder
      DisplayName: !Sub ${ProjectName}-appstream-windows-image-builder
      Description: Windows Server 2019 Image Builder for AppStream 2.0
      AppstreamAgentVersion: LATEST
      EnableDefaultInternetAccess: !Ref EnableDefaultInternetAccess
      ImageName: AppStream-WinServer2019-03-29-2023
      InstanceType: !Ref InstanceType
      IamRoleArn:
        Fn::ImportValue: !Sub ${AWS::Region}-${S3StackName}-AppStreamS3BucketRoleArn
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-windows-image-builder
  AppStreamLinuxImageBuilder:
    Type: AWS::AppStream::ImageBuilder
    Properties:
      Name: !Sub ${ProjectName}-appstream-linux-image-builder
      DisplayName: !Sub ${ProjectName}-appstream-linux-image-builder
      Description: Amazon Linux 2 Image Builder for AppStream 2.0
      AppstreamAgentVersion: LATEST
      EnableDefaultInternetAccess: !Ref EnableDefaultInternetAccess
      ImageName: AppStream-AmazonLinux2-03-15-2023
      InstanceType: !Ref InstanceType
      IamRoleArn:
        Fn::ImportValue: !Sub ${AWS::Region}-${S3StackName}-AppStreamS3BucketRoleArn
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-windows-image-builder
Outputs:
  AppStreamWindowsImageBuilder:
    Value: !Ref AppStreamWindowsImageBuilder
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamWindowsImageBuilder
  AppStreamLinuxImageBuilder:
    Value: !Ref AppStreamLinuxImageBuilder
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamLinuxImageBuilder
