---
AWSTemplateFormatVersion: 2010-09-09
Description: AppStream 2.0 image builder
Parameters:
  VpcStackName:
    Description: Set the VPC stack name.
    Type: String
    Default: vpc-private-subnets-with-gateway-endpoints
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: iam-role-for-appstream
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: vdi
  ImageName:
    Description: Set the AppStream 2.0 image name.
    Type: String
    Default: AppStream-AmazonLinux2-03-15-2023
  InstanceType:
    Description: Set the AppStream 2.0 instance type.
    Type: String
    Default: stream.standard.small
  EnableDefaultInternetAccess:
    Description: Enable the default internet access.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
Resources:
  AppStreamImageBuilder:
    Type: AWS::AppStream::ImageBuilder
    Properties:
      Name: !Sub ${ProjectName}-appstream-image-builder-${ImageName}
      DisplayName: !Sub ${ProjectName}-appstream-image-builder-${ImageName}
      Description: !Sub AppStream 2.0 Image Builder (${ImageName})
      # AppstreamAgentVersion: LATEST
      EnableDefaultInternetAccess: !Ref EnableDefaultInternetAccess
      ImageName: !Ref ImageName
      InstanceType: !Ref InstanceType
      IamRoleArn:
        Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-AppStreamServiceRoleArn
      VpcConfig:
        SubnetIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
      # AccessEndpoints:
      #   - EndpointType: STREAMING
      #     VpceId: !Ref AppStreamStreamingInterfaceEndpoint
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-image-builder-${ImageName}
#   AppStreamStreamingInterfaceEndpoint:
#     Type: AWS::EC2::VPCEndpoint
#     Properties:
#       PrivateDnsEnabled: true
#       SubnetIds:
#         - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-PrivateSubnet0
#       SecurityGroupIds:
#         - Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-DefaultSecurityGroup
#       ServiceName: !Sub com.amazonaws.${AWS::Region}.appstream.streaming
#       VpcEndpointType: Interface
#       VpcId:
#         Fn::ImportValue: !Sub ${AWS::Region}-${VpcStackName}-VPC
Outputs:
  AppStreamImageBuilder:
    Value: !Ref AppStreamImageBuilder
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamImageBuilder
#   AppStreamStreamingInterfaceEndpointId:
#     Description: AppStream streaming interface endpoint Id
#     Value: !Ref AppStreamStreamingInterfaceEndpoint
#     Export:
#       Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamStreamingInterfaceEndpoint
