---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM roles for AppStream 2.0
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: vdi
Resources:
  AppStreamServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-AppStreamServiceRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appstream.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAppStreamServiceAccess
      Policies:
        - PolicyName: !Sub ${ProjectName}-assume-role-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sts:AssumeRole
                Resource:
                  - !Sub arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-AppStreamServiceRole
        - PolicyName: !Sub ${ProjectName}-s3-access-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:Describe*
                  - s3:Get*
                  - s3:List*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                Resource:
                  - !Sub arn:aws:s3:::${ProjectName}-*
              - Effect: Allow
                Action:
                  - s3:Describe*
                  - s3:Get*
                  - s3:List*
                  - s3:*Object*
                  - s3:*MultipartUpload*
                  - s3-object-lambda:Get*
                  - s3-object-lambda:List*
                  - s3-object-lambda:*Object*
                  - s3-object-lambda:*MultipartUpload*
                Resource:
                  - !Sub arn:aws:s3:::${ProjectName}-*/*
        - PolicyName: !Sub ${ProjectName}-efs-access-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:Describe*
                  - elasticfilesystem:List*
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                Resource:
                  - !Sub arn:aws:elasticfilesystem:${AWS::Region}:${AWS::AccountId}:*/*
  AppStreamAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-AppStreamAutoScalingRole
      Path: /
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - application-autoscaling.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/ApplicationAutoScalingForAmazonAppStreamAccess
Outputs:
  AppStreamServiceRoleArn:
    Value: !GetAtt AppStreamServiceRole.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamServiceRoleArn
  AppStreamAutoScalingRoleArn:
    Value: !GetAtt AppStreamAutoScalingRole.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamAutoScalingRoleArn
