---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for AppStream 2.0
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: vdi
Resources:
  AppStreamS3Bucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub ${ProjectName}-appstream-${AWS::AccountId}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: Move-to-Intelligent-Tiering-after-0day
            Status: Enabled
            Transitions:
              - TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
              NoncurrentDays: 7
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-appstream-${AWS::AccountId}
        - Key: ProjectName
          Value: !Ref ProjectName
  AppStreamS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppStreamS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowRetrievalPermissionsToS3AppsForAppStream
            Effect: Allow
            Principal:
              Service: appstream.amazonaws.com
            Action:
              - s3:GetObject
            Resource:
              - Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - !Ref AppStreamS3Bucket
                    - /*
Outputs:
  AppStreamS3Bucket:
    Value: !Ref AppStreamS3Bucket
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppStreamS3Bucket
